version: '3.9'
services:
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crowdfunding
    volumes:
      - data:/var/lib/postgresql/data


volumes:
  data: